version: '3'

services:
  db:
    image: postgres:13.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - default

volumes:
  db:
    driver: local
